name: Typescript CI
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Set up tools on Ubuntu
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - run: npm ci
      - run: make lint
